services:
# Database service
  db:
    build: ./db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER -h db || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 30s
  
  # Initialize database service
  init-db:
    build: ./init
    depends_on:
      db:
        condition: service_healthy
